### PR TITLE
Fix for Python 3.10 and newer

### PR DESCRIPTION
**Pull request by stweil**

### CODE REVIEW

**Comment by stweil** [comment]
The fix is required on Debian stable which uses Python 3.11.

**Comment by mikegerber** [comment]
Thanks, @stweil! 

Do you use this regularily? For me it was rather a one-off script to fix some issues with existing GT. It would be valuable to have some feedback that this is wanted. And to look into merging it into ocrd-segment-repair (or similar). It also is badly named in the same way I've complained about elsewhere 🤭 (too broad)

👀 @kba @bertsky

**Comment by mikegerber** [comment]
LGTM, merging untested

**Comment by stweil** [comment]
> Do you use this regularily?

No, sorry. But it is part of ocrd_all, and the build process checks run all processors...

**Pull request merged**
